services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Belsignum\Languagemodes\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Belsignum\Languagemodes\Xclass\SiteConfiguration:
    arguments:
      $coreCache: '@cache.core'
      $configPath: '%env(TYPO3:configPath)%/sites'

